apiVersion: v1
kind: Service
metadata:
  name: {{ include "soroban-rpc-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soroban-rpc-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "soroban-rpc-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: rpc
